use axum::Router;
use synfony_config::SynfonyConfig;
use synfony_di::Container;
use tower_http::cors::CorsLayer;
use tower_http::trace::TraceLayer;

use crate::state::AppState;

/// The HTTP Kernel — equivalent to Symfony's HttpKernel.
///
/// Responsible for building the Axum application with all middleware,
/// routes, and services wired together.
pub struct Kernel {
    state: AppState,
    router: Router<AppState>,
}

impl Kernel {
    pub fn new(config: SynfonyConfig, container: Container) -> Self {
        let state = AppState::new(container, config);
        let router = Router::new();

        Kernel { state, router }
    }

    /// Register a controller's routes with the kernel.
    ///
    /// Controllers generate their own Router via the `routes()` method
    /// (generated by the `#[controller]` macro).
    pub fn register_routes(mut self, routes: Router<AppState>) -> Self {
        self.router = self.router.merge(routes);
        self
    }

    /// Add Tower middleware layers.
    pub fn with_default_middleware(self) -> Self {
        // Default middleware stack — equivalent to Symfony's default event listeners
        self
    }

    /// Build the final Axum application ready to serve.
    pub fn build(self) -> Router {
        let is_debug = self.state.config.is_debug();

        let mut app = self.router;

        // Add default middleware
        if is_debug {
            app = app.layer(TraceLayer::new_for_http());
        }

        app = app.layer(CorsLayer::permissive());

        app.with_state(self.state)
    }
}
